In [3]:
%matplotlib  inline

import numpy  as np
import matplotlib as plt
import pandas as pd

#數據分析最重要的三個

In [3]:
grades=[50,60,44,62,67,87,56]

In [6]:
curved = []

for g in grades:
    curved.append(g*1.1)

In [7]:
grades

[50, 60, 44, 62, 67, 87, 56]

In [11]:
curved2 = []

for g in curved:
    curved2.append(g+4)

In [12]:
curved

[55.00000000000001,
 66.0,
 48.400000000000006,
 68.2,
 73.7,
 95.7,
 61.60000000000001]

In [13]:
curved2

[59.00000000000001,
 70.0,
 52.400000000000006,
 72.2,
 77.7,
 99.7,
 65.60000000000001]

In [14]:
grad_arr = np.array(grades)

In [15]:
grad_arr 


array([50, 60, 44, 62, 67, 87, 56])

In [17]:
grad_arr*1.1+4

array([59. , 70. , 52.4, 72.2, 77.7, 99.7, 65.6])

Broadcasting!! 一個一個傳遞到 array 之中

In [32]:
weight=[0.1,0.3,0.1,0.1,0.2,0.1,0.1]

In [33]:
weight_arr =np.array(weight)

In [34]:
grad_arr*weight_arr

array([ 5. , 18. ,  4.4,  6.2, 13.4,  8.7,  5.6])

In [36]:
grad_arr@weight_arr

#dot product

61.3

In [40]:
grades=np.array([[12,14,15],
                        [34,52,54],           
                        [100,90,80]] )

In [43]:
weight=np.array([0.3,0.3,0.4])

In [47]:
wgrade=grades*weight
wgrade


array([[ 3.6,  4.2,  6. ],
       [10.2, 15.6, 21.6],
       [30. , 27. , 32. ]])

In [46]:
wgrade.sum(axis=1)

array([13.8, 47.4, 89. ])

In [48]:
weight.shape

(3,)

In [52]:
weightmat=weight.reshape(3,1)

In [54]:
grades@weightmat

array([[13.8],
       [47.4],
       [89. ]])

In [69]:
a=np.random.randint(0,2,50)

In [70]:
a.shape

(50,)

In [66]:
a.shape=(5,10) 
#乘起來一定要是50
#用reshape較優

In [74]:
a.reshape(5,10)

array([[0, 0, 1, 1, 1, 1, 1, 1, 0, 1],
       [0, 1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 1, 0, 0, 0, 1, 1, 1, 1, 0]])

In [75]:
a=a.reshape

In [78]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [79]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [83]:
np.ones([5,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [85]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [86]:
a=np.array([[12,14,15],
             [34,52,54],           
            [100,90,80]] )

In [88]:
np.diag(a)

array([12, 52, 80])

In [89]:
L=np.array([1,4423,-234,-211,10])

In [90]:
want  =np.array([True,True,False,False,True])

In [91]:
L[want]

array([   1, 4423,   10])

In [92]:
L>0

array([ True,  True, False, False,  True])

In [93]:
L[L>0 ]
#裡面為布林值的array

array([   1, 4423,   10])

In [96]:
L[(L>0) & (L<11)]
#小刮號刮起條件

array([ 1, 10])

In [106]:
x=np.linspace(-5,5,100)
y=np.sinc(x)

plt.plt(x,y)

AttributeError: module 'matplotlib' has no attribute 'plt'

In [107]:
import sympy as sym

In [108]:
1/2 + 1/3

0.8333333333333333

In [109]:
sym.S(1)/2+sym.S(1)/3

5/6

In [117]:
from sympy import S ,  N

In [120]:
sym.isprime(157)

True

In [121]:
for i in range(2,50):
    a = sym.prime(i)
    b = sym.prime(i+1)
    if b-a == 2:
        print(f'{a} 和 {b}  是孿生質數')

3 和 5  是孿生質數
5 和 7  是孿生質數
11 和 13  是孿生質數
17 和 19  是孿生質數
29 和 31  是孿生質數
41 和 43  是孿生質數
59 和 61  是孿生質數
71 和 73  是孿生質數
101 和 103  是孿生質數
107 和 109  是孿生質數
137 和 139  是孿生質數
149 和 151  是孿生質數
179 和 181  是孿生質數
191 和 193  是孿生質數
197 和 199  是孿生質數
227 和 229  是孿生質數


In [122]:
A = sym.Matrix([[2,-1,3],
                      [0,1,2],
                      [-1,1,2]])


In [123]:
A.det()

5

In [124]:
A.inv()

Matrix([
[   0,    1,   -1],
[-2/5,  7/5, -4/5],
[ 1/5, -1/5,  2/5]])

不會出現浮點數 會出現小數

In [125]:
x = sym.Symbol("x")

In [131]:
from sympy.abc import x, y, z

pandas 清資料

In [11]:
a=np.eye(10)*5

In [12]:
b=np.diag([1,2,3,4,5,6,7,8,9,10])

In [13]:
a*b

array([[ 5.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 15.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 20.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 25.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 30.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., 35.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 40.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 45.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 50.]])